client/webpack.config.js
- 새로고침이 정상적으로 동작하지 않는 문제가 있었음
- webpack.config.js의 devServer 프로퍼티에 index.html 경로를 수정함
=> webpack-dev-server에서 새로고침이 정상적으로 동작하지 않는 문제 해결

client/package.json
- resolve #22 
- `package.json`에 relay watch 스크립트 추가
- 추가하면 좋을 것 같은 스크립트 추가해봤어요!
=> relay watch 스크립트 추가해라

client/src/hocs/withSuspense.tsx, client/src/page/LoginCallbackPage.tsx
- 기존에 QueryRender를 사용하는 로직이 어색하다고 느껴서 수정함
- useLazyLoadQuery를 사용하는걸로 변경함
=> LoginCallbackPage 로직 수정

client/src/App.tsx, client/src/__generated__/CommentPageQuery.graphql.ts, client/src/__generated__/Comment_comment.graphql.ts, client/src/components/Example/Comment.tsx, client/src/graphql/schema.graphql, client/src/page/CommentPage.tsx, server/package.json, server/src/db/comment.json, server/src/models/commentModel.ts, server/src/repositories/commentRepository.ts, server/src/services/comment/commentResolver.ts, server/src/services/comment/commentType.ts, server/src/services/index.ts, server/yarn.lock
- 댓글을 볼 수 있게 함
- Comment 관련 서버로직 추가
- Commen 를 볼 수 있는 CommentPage 구현
- `/comment`에서 확인할 수 있습니다.
- 임시로 commentPage를 만들었습니다. 문제가 페이지별로 보여질때 로직 수정할 예정입니다.
=> 댓글 보기 기능 구현

client/src/App.tsx, client/src/__generated__/BookmarksPageQuery.graphql.ts, client/src/graphql/schema.graphql, client/src/page/BookmarksPage.tsx
- resolve #42
- feat: 북마크 목록 페이지에 북마크 목록 보기 기능 추가
=> [Client] 북마크 목록 페이지에 북마크 목록 보기 기능 추가

client/package.json, client/yarn.lock, server/package.json, server/yarn.lock
- resolve #46
- 클라이언트에서 husky 사용하도록 설정
- 서버에서 husky 사용하도록 설정  
- CI 쪽에서 lint, test 잡아도 되지만, 그렇게 될 경우 commit 이 깔끔하지 않게 관리되더라구요
- 그래서 local에서 미리 잡는게 좋을 것 같아서 제안합니다.
- 혹시나, husky 모르시는 분을 위해 [한글용 자료](https://www.huskyhoochu.com/npm-husky-the-git-hook-manager/) 첨부합니다.
=> commit, push 시 lint 체크를 위한 husky를 사용해라

client/src/App.tsx, client/src/__generated__/BookmarksPageQuery.graphql.ts, client/src/graphql/schema.graphql, client/src/page/BookmarksPage.tsx, client/test/e2e/bookmarks_page.test.js, server/src/db/bookmark.json, server/src/models/bookmarkModel.ts, server/src/models/questionModel.ts, server/src/repositories/bookmarkRepository.ts, server/src/repositories/questionRepository.ts, server/src/services/bookmark/bookmarkResolver.ts, server/src/services/bookmark/bookmarkType.ts, server/src/services/index.ts
=> 북마크 목록 페이지에서 북마크 목록 보기 기능 구현

client/package.json
- lint 실행 명령어가 빠져서
- lint 명령어 추가
=> 빠진 lint 명령어를 추가해라

client/package.json, client/src/App.tsx, client/src/helper/Errorboundary.tsx, client/src/index.tsx, client/yarn.lock
- 에러 발생시, 사용자에게 빈 화면을 대신한 UI를 보여주기 위해 Errorboundary 도입
- Sentry 설치
- Errorboundary 구현
- 기본 fallback 구현
- Sentry에서 테스트도 완료했어요~
=> Errorboundary 구현

.github/workflows/server.yml, server/start.sh
- resolve #63
서버 자동 배포
env 파일 추가 처리 필요
=> 서버 ec2 github action workflow

.github/workflows/client.yml
- resolve #62
클라이언트 자동 배포 워크 플로우
dev-answer 깃헙 토큰 필요
빌드 잘 되는지 추가 확인 필요
=> 클라이언트 github page github action workflow

.github/workflows/client.yml
=> client workflow 오타 수정

.github/workflows/server.yml, server/package.json, server/production.sh, server/start.sh
배포, 개발 스크립트 분리 필요.
서버 stop 명령어 안되는 현상
서버 워크플로우 수정, start script 복구, production script 생성
=> 서버 워크플로우 수정, start script 복구, production script 생성 

server/src/models/bookmarkModel.ts, server/src/repositories/bookmarkRepository.ts, server/src/services/bookmark/bookmarkResolver.ts, server/src/services/bookmark/bookmarkType.ts
- resolve #72 
- BookmarkModel에 removeOne 추가
- BookmarkRepository에 removeOne 추가
- BookmarkResolver에 removeBookmark Mutation 추가
- 북마크 취소 테스트 완료!
=> [Server] 북마크 취소

.github/workflows/client.yml
- 보안상 필요하다고 생각해서
- secret에 해당 값 추가 후 workflow에서 주입해준다.
=> SENTRY_DSN를 secrect으로 관리

client/src/components/common/PageNavigator.tsx, client/src/index.tsx
- 놓친 부분들에 대해 콘솔에서 warning이 발생하고 있었음.
- attribute명 변경 target -> selected
- key값 부여
=> PageNavigator 컴포넌트에서 발생하는 warning 대응

client/.eslintrc.js, client/src/index.tsx, server/.eslintrc.js, server/src/models/bookmarkModel.ts, server/src/models/userModel.ts
- eslint rule에서 ts의 rule을 사용하도록 설정
=> TS 타입에서 no-unused-vars 린트에러가 나는 문제 해결

.github/workflows/server.yml, server/production.sh
forever 로 할시 github action timeout 발생하여 action 이 안된것 처럼 결과가 뜸
pm2 로 변경
=> [Server] change server workflow

.github/workflows/server.yml
- github action으로 sudo로 실행시 yarn 및 pm2 못 찾는 문제 및 pm2 sync 안된 이슈
- script에서 sudo 제거 및 pm2 save로 sync
=> [Server] update server.yml

.github/workflows/client.yml, client/src/graphql/index.ts
- env 적용 안됬던 이슈
action 도중에 .env 파일 생성하여 사용
=> update client workflow

client/src/components/common/BottomSheet.tsx, client/src/constants/style.ts, client/src/contexts/RootElement.tsx, client/src/index.tsx, client/src/page/QuestionBoardPage.tsx, client/src/style/index.tsx
- QuestionDetailPage에서 하단 카드들에 마우스 오버시 필요한 애니메이션이 있어서 이를 위한 컴포넌트를 구현함
- BottomSheet 컴포넌트 구현 및 애니메이션 style 관리
사용 방법
```
<BottomSheet>
<div>
// 여기에 필요한 children 컴포넌트 추가
</div>
</BottomSheet>
```
=> BottomSheet 컴포넌트 구현

server/src/db/question.json, server/src/services/question/questionType.ts, server/src/types/question.ts
- 문제 상세 페이지에서 "정보"에 대한 데이터가 필요함
- 이를 위해 DB에 데이터를 추가하고 type을 추가함
=> 서버에서 내려주는 question response에 문제 정보 추가

server/src/db/question.json, server/src/models/questionModel.ts, server/src/repositories/questionRepository.ts, server/src/services/question/questionResolver.ts, server/src/services/question/questionType.ts, server/src/types/question.ts
- 문제에 대한 난이도(쉬워요, 좋아요, 어려워요)를 투표할 수 있는 기능이 있어서 이에 대한 서버 로직을 구현함
- vote Mutation 구현
=> 문제 투표 기능 서버 로직 구현

client/src/__generated__/QuestionDetailCardVoteMutation.graphql.ts, client/src/__generated__/QuestionDetailCard_question.graphql.ts, client/src/__generated__/QuestionDetailCard_user.graphql.ts, client/src/__generated__/QuestionDetailPageQuery.graphql.ts, client/src/components/Question/QuestionDetailCard.tsx, client/src/graphql/schema.graphql, client/src/page/QuestionDetailPage.tsx, server/src/models/questionModel.ts, server/src/services/question/questionType.ts
(북마크 버튼 깜빡이는거는 로직이 임시구현되어있어서 그렇슴당)
- optimisticUpdater 더 좋게 구현할 수 있는 방법이 있다면 알려주세요!
=> 문제 상세 페이지 Question 부분 UI 구현 마무리 및 투표기능 구현
